version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4

parameters:
  workflow:
    description: |
      String that controls which workflow would run.
      This parameter is used by automation to determine if a workflow will run
      within a pipeline.
    type: string
    default: 'test-and-release'

jobs:
  build_and_test:
    resource_class: medium
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test
  build_and_test_windows:
    executor: win/server-2022
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  test-and-release:
    jobs:
      - build_and_test
      - build_and_test_windows:
          requires:
            - build_and_test
      - release-management/release-package:
          github-release: true
          requires:
            - build_and_test_windows
          filters:
            branches:
              only: main
          context:
            - release
  dependabot-automerge:
    when:
      equal: [dependabot-automerge, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/dependabot-automerge:
          context: release
