name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
  linux-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@main
  windows-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsWindows.yml@main
  lint-external:
    uses: ./.github/workflows/externalLint.yml
    needs: [linux-unit-tests]
    strategy:
      fail-fast: false
      matrix:
        externalProjectGitUrl:
          - https://github.com/salesforcecli/plugin-deploy-retrieve
          - https://github.com/salesforcecli/plugin-env
          - https://github.com/salesforcecli/plugin-settings
          - https://github.com/salesforcecli/plugin-login
          - https://github.com/salesforcecli/plugin-sobject
          - https://github.com/salesforcecli/plugin-dev
          - https://github.com/salesforcecli/plugin-limits
          - https://github.com/salesforcecli/plugin-schema
    with:
      packageName: 'eslint-plugin-sf-plugin'
      externalProjectGitUrl: ${{ matrix.externalProjectGitUrl }}
      preBuildCommands: yarn remove @types/jest
