name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
  linux-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@cd/fix-bool
    with:
      skipTsDepCheck: true
  windows-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsWindows.yml@main
  lint-external:
    uses: ./.github/workflows/externalLint.yml
    needs: [linux-unit-tests]
    strategy:
      fail-fast: false
      matrix:
        externalProjectGitUrl:
          - https://github.com/salesforcecli/plugin-auth
          - https://github.com/salesforcecli/plugin-apex
          - https://github.com/salesforcecli/plugin-community
          - https://github.com/salesforcecli/plugin-custom-metadata
          - https://github.com/salesforcecli/plugin-data
          - https://github.com/salesforcecli/plugin-deploy-retrieve
          - https://github.com/salesforcecli/plugin-dev
          - https://github.com/salesforcecli/plugin-info
          - https://github.com/salesforcecli/plugin-limits
          - https://github.com/salesforcecli/plugin-org
          - https://github.com/salesforcecli/plugin-packaging
          - https://github.com/salesforcecli/plugin-schema
          - https://github.com/salesforcecli/plugin-settings
          - https://github.com/salesforcecli/plugin-signups
          - https://github.com/salesforcecli/plugin-sobject
          - https://github.com/salesforcecli/plugin-templates
          - https://github.com/salesforcecli/plugin-user
        command:
          - yarn eslint "src/**/*.ts" --fix
          - yarn eslint "src/**/*.ts"
    with:
      packageName: 'eslint-plugin-sf-plugin'
      externalProjectGitUrl: ${{ matrix.externalProjectGitUrl }}
      preBuildCommands: yarn remove @types/jest
      command: ${{ matrix.command }}
